// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjOII-qV6pPYfKgqx6vzunKc2la-JLGH4',
    appId: '1:249430847916:web:49034d51a1eebac9c14a09',
    messagingSenderId: '249430847916',
    projectId: 'khanakhazana-f5c79',
    authDomain: 'khanakhazana-f5c79.firebaseapp.com',
    storageBucket: 'khanakhazana-f5c79.appspot.com',
    measurementId: 'G-29EYGWP70Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-R8RrIeEn26bDVJxk93Mlp0EFfobEEc',
    appId: '1:249430847916:android:c959bd483b0499fdc14a09',
    messagingSenderId: '249430847916',
    projectId: 'khanakhazana-f5c79',
    storageBucket: 'khanakhazana-f5c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycDAxjES_GZPOJXrcb6eza2MSUFbuTSQ',
    appId: '1:249430847916:ios:30fdccec9bc5975fc14a09',
    messagingSenderId: '249430847916',
    projectId: 'khanakhazana-f5c79',
    storageBucket: 'khanakhazana-f5c79.appspot.com',
    iosBundleId: 'com.example.khanakhazana',
  );
}
